# Generated by Django 5.1.7 on 2025-03-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='ბრენდი')),
                ('model', models.CharField(max_length=100, verbose_name='მოდელი')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ფასი')),
                ('processor', models.CharField(max_length=100, verbose_name='პროცესორი')),
                ('ram', models.IntegerField(verbose_name='ოპერატიული მეხსიერება (გბ)')),
                ('storage', models.IntegerField(verbose_name='შიდა მეხსიერება (გბ)')),
                ('display', models.CharField(max_length=100, verbose_name='ეკრანი')),
                ('graphics', models.CharField(max_length=100, verbose_name='გრაფიკა')),
            ],
            options={
                'verbose_name': 'ლეპტოპი',
                'verbose_name_plural': 'ლეპტოპები',
            },
        ),
    ]
